from pyspark.sql.types import (IntegerType, LongType, StringType, StructField,
                               StructType)
from sedona.sql.types import GeometryType

from osm_address.transform import create_border_polygons


class TestCreateBorders:

    def test_border_schema(self, test_context):

        df_res = create_border_polygons(
            osm_data=test_context.osm_data,
            relation_filter="id=7790585",
            additional_columns={
                "region": "IFNULL(element_at(tags, 'name:de'), element_at(tags, 'name'))"
            },
            result_polygon_name="result_polygon"
        ).orderBy(
            "id"
        )

        assert df_res.schema == StructType([
            StructField("region", StringType(), True),
            StructField("result_polygon", GeometryType(), True)
        ])

    def test_border_schema_no_add_columns(self, test_context):

        df_res = create_border_polygons(
            osm_data=test_context.osm_data,
            relation_filter="id=7790585"
        ).orderBy(
            "id"
        )

        assert df_res.schema == StructType([
            StructField("multipolygon", GeometryType(), True)
        ])

    def test_border_debug_schema(self, test_context):

        df_res = create_border_polygons(
            osm_data=test_context.osm_data,
            relation_filter="id=7790585",
            additional_columns={
                "region": "IFNULL(element_at(tags, 'name:de'), element_at(tags, 'name'))"
            },
            add_debug_columns=True
        ).orderBy(
            "id"
        )

        assert df_res.schema == StructType([
            StructField("region", StringType(), True),
            StructField("multipolygon", GeometryType(), True),
            StructField("id", LongType(), True),
            StructField("outer_polygon_count", IntegerType(), True),
            StructField("inner_polygon_count", IntegerType(), True),
            StructField("outer_point_count", IntegerType(), True),
            StructField("inner_point_count", IntegerType(), True),
            StructField("invalidity_explain", StringType(), True)
        ])

    def test_border(self, test_context):

        df_res = create_border_polygons(
            osm_data=test_context.osm_data,
            relation_filter="id=7790585 OR 1=1",
            additional_columns={
                "region": "IFNULL(element_at(tags, 'name:de'), element_at(tags, 'name'))"
            },
            add_debug_columns=True
        ).orderBy(
            "id"
        )
        df_res.cache()

        # check number of valid multipolygons
        assert df_res.count() == 56

        stat_values = []
        # check if all are valid
        res = df_res.collect()
        for row in res:
            poly = row["multipolygon"]
            assert poly.is_valid

            stat_values.append({
                "region": row["region"],
                "id": row["id"],
                "outer_polygon_count": row["outer_polygon_count"],
                "inner_polygon_count": row["inner_polygon_count"],
                "outer_point_count": row["outer_point_count"],
                "inner_point_count": row["inner_point_count"],
                "invalidity_explain": row["invalidity_explain"]
            })

            if row["invalidity_explain"] is None:
                assert row["outer_polygon_count"] == len(list(poly.geoms)), \
                    f"Outer polygon counts don't match for {row['id']}"

        assert stat_values == [{'id': 9407,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 901,
                                'outer_polygon_count': 1,
                                'region': 'Andorra'},
                               {'id': 411235,
                                'inner_point_count': 222,
                                'inner_polygon_count': 6,
                                'invalidity_explain': None,
                                'outer_point_count': 368,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 1161383,
                                'inner_point_count': 428,
                                'inner_polygon_count': 8,
                                'invalidity_explain': None,
                                'outer_point_count': 134,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 1477177,
                                'inner_point_count': 14,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 20,
                                'outer_polygon_count': 1,
                                'region': "Estany de l'Isla"},
                               {'id': 1477179,
                                'inner_point_count': 16,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 68,
                                'outer_polygon_count': 1,
                                'region': 'Estany Primer de Juclar'},
                               {'id': 1837358,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 95,
                                'outer_polygon_count': 1,
                                'region': "L'Hospitalet-près-l'Andorre"},
                               {'id': 2679449,
                                'inner_point_count': 90,
                                'inner_polygon_count': 4,
                                'invalidity_explain': None,
                                'outer_point_count': 183,
                                'outer_polygon_count': 1,
                                'region': "Estany de l'Illa"},
                               {'id': 2800131,
                                'inner_point_count': 186,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 2631,
                                'outer_polygon_count': 2,
                                'region': 'Naturpark Hohe Pyrenäen'},
                               {'id': 2804753,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 106,
                                'outer_polygon_count': 1,
                                'region': 'Andorra la Vella'},
                               {'id': 2804754,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 322,
                                'outer_polygon_count': 1,
                                'region': 'Canillo'},
                               {'id': 2804755,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 299,
                                'outer_polygon_count': 1,
                                'region': 'Encamp'},
                               {'id': 2804756,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 260,
                                'outer_polygon_count': 1,
                                'region': 'Escaldes-Engordany'},
                               {'id': 2804757,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 350,
                                'outer_polygon_count': 1,
                                'region': 'La Massana'},
                               {'id': 2804758,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 290,
                                'outer_polygon_count': 1,
                                'region': 'Ordino'},
                               {'id': 2804759,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 166,
                                'outer_polygon_count': 1,
                                'region': 'Sant Julià de Lòria'},
                               {'id': 2813720,
                                'inner_point_count': 45,
                                'inner_polygon_count': 3,
                                'invalidity_explain': None,
                                'outer_point_count': 394,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 2813721,
                                'inner_point_count': 10,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 41,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 2995070,
                                'inner_point_count': 5,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 26,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 3657693,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 132,
                                'outer_polygon_count': 1,
                                'region': 'Andorra la Vella'},
                               {'id': 3657694,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 69,
                                'outer_polygon_count': 1,
                                'region': 'Santa Coloma'},
                               {'id': 3657696,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 14,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 4193665,
                                'inner_point_count': 5,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 12,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 4193666,
                                'inner_point_count': 5,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 14,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 4193667,
                                'inner_point_count': 10,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 11,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 4639046,
                                'inner_point_count': 28,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 106,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 4639171,
                                'inner_point_count': 22,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 128,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5251933,
                                'inner_point_count': 12,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 16,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5308473,
                                'inner_point_count': 159,
                                'inner_polygon_count': 5,
                                'invalidity_explain': None,
                                'outer_point_count': 87,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5475321,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 49,
                                'outer_polygon_count': 1,
                                'region': 'Estany Gran de la Vall del Riu'},
                               {'id': 5489222,
                                'inner_point_count': 21,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 96,
                                'outer_polygon_count': 1,
                                'region': 'Estany de Montmalús'},
                               {'id': 5491701,
                                'inner_point_count': 99,
                                'inner_polygon_count': 3,
                                'invalidity_explain': None,
                                'outer_point_count': 187,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5675807,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 313,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5675808,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 748,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5675809,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 321,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5676135,
                                'inner_point_count': 61,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 110,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5676210,
                                'inner_point_count': 57,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 913,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5710272,
                                'inner_point_count': 110,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 288,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5734196,
                                'inner_point_count': 14,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 35,
                                'outer_polygon_count': 1,
                                'region': 'Estany Segon de Juclar'},
                               {'id': 5761660,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 64,
                                'outer_polygon_count': 1,
                                'region': 'Parc Natural de la Vall de Sorteny'},
                               {'id': 5761670,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 188,
                                'outer_polygon_count': 1,
                                'region': 'Parc Natural Comunal de les Valls del Comapedrosa'},
                               {'id': 5877497,
                                'inner_point_count': 44,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 264,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5877498,
                                'inner_point_count': 380,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 250,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 5881919,
                                'inner_point_count': 123,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 194,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 6106461,
                                'inner_point_count': 18,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 43,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7292210,
                                'inner_point_count': 118,
                                'inner_polygon_count': 6,
                                'invalidity_explain': None,
                                'outer_point_count': 204,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7336278,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 16,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7630873,
                                'inner_point_count': 5,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 5,
                                'outer_polygon_count': 1,
                                'region': 'centre esportiu de Sant Julia de Loria'},
                               {'id': 7790584,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 7,
                                'outer_polygon_count': 1,
                                'region': 'Sant Serni'},
                               {'id': 7790585,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': 'Self-intersection[1.5975612 42.5675810000002]',
                                'outer_point_count': 16,
                                'outer_polygon_count': 2,
                                'region': 'Sant Serni'},
                               {'id': 7947924,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 247,
                                'outer_polygon_count': 1,
                                'region': 'Naturlandia'},
                               {'id': 7947925,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 41,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7947926,
                                'inner_point_count': 247,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 442,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7980888,
                                'inner_point_count': 10,
                                'inner_polygon_count': 2,
                                'invalidity_explain': None,
                                'outer_point_count': 9,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 7980889,
                                'inner_point_count': 5,
                                'inner_polygon_count': 1,
                                'invalidity_explain': None,
                                'outer_point_count': 5,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 8473237,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 126,
                                'outer_polygon_count': 1,
                                'region': None},
                               {'id': 8473238,
                                'inner_point_count': 0,
                                'inner_polygon_count': 0,
                                'invalidity_explain': None,
                                'outer_point_count': 9,
                                'outer_polygon_count': 1,
                                'region': None}]
